### ISSUE TITLE
EOFException

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#68] opened 2015-10-09 07:03 UTC
I was debugging why i am getting EOF exceptions frequently for only few clusters out of 20 mysql clusters. 

In ByteArrayInputStream.java, skipToTheEndOfTheBlock(), i have put some catch where i got this, num of bytes skipped:-1, 261   ( -1 is number of bytes skipped, 261 is number of bytes to be skipped)

in EventDeserializer, on exception i have put a print like this too, 
 EventDataDeserializationException:java.io.EOFException , 669 , 0 ( 669 is event body length, 0 is checksumLength)

 below is the event header and the exception trace,
Communication failure, BinLog: bin.006476 505909 clientServerId: 2089416623 Cause: java.io.EOFException Exception: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1443596307000, eventType=UPDATE_ROWS, serverId=22172059, headerLength=19, dataLength=669, nextPosition=506597, flags=0}

Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:187)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:48)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:150)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:99)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:72)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:183)
        ... 18 more

Could you tell me, whether blockLength is getting updated wrongly?

**Comment by syed72** [comment] 2015-10-09 11:42
Below is the output before throwing EOF exception,

EventHeaderV4{timestamp=1443605718000, eventType=WRITE_ROWS, serverId=22172059, headerLength=19, dataLength=391, nextPosition=416904, flags=0}, eventType:WRITE_ROWS
EnterBlock: 391 (THis is in enterBlock() method of ByteArrayInputStream class)
rwbb: 390  (here rwbb is readwithin block boundaries method return value and read() method giving result, blockLength is eventBodyLength this is just FYI ),
read(): 10,peek: null, blockLength:390
rwbb: 389
read(): 90,peek: null, blockLength:389
rwbb: 388
read(): 107,peek: null, blockLength:388
rwbb: 387
read(): 9,peek: null, blockLength:387
rwbb: 386
read(): 0,peek: null, blockLength:386
rwbb: 385
read(): 0,peek: null, blockLength:385
rwbb: 384
read(): 1,peek: null, blockLength:384
rwbb: 383
read(): 0,peek: null, blockLength:383
rwbb: 382
read(): 31,peek: null, blockLength:382
rwbb: 381
read(): 255,peek: null, blockLength:381
rwbb: 380
read(): 255,peek: null, blockLength:380
rwbb: 379
read(): 255,peek: null, blockLength:379
rwbb: 378
read(): 255,peek: null, blockLength:378
rwbb: 377
read(): 0,peek: null, blockLength:377
rwbb: 376
read(): 0,peek: null, blockLength:376
rwbb: 375
read(): 0,peek: null, blockLength:375
rwbb: 374
read(): 130,peek: null, blockLength:374
rwbb: 373
read(): 244,peek: null, blockLength:373
rwbb: 372
read(): 39,peek: null, blockLength:372
rwbb: 371
read(): 1,peek: null, blockLength:371
rwbb: 370
read(): 0,peek: null, blockLength:370
rwbb: 369
read(): 0,peek: null, blockLength:369
rwbb: 368
read(): 0,peek: null, blockLength:368
rwbb: 367
read(): 0,peek: null, blockLength:367
rwbb: 366
read(): 0,peek: null, blockLength:366
rwbb: 365
read(): 19,peek: null, blockLength:365
rwbb: 364
read(): 0,peek: null, blockLength:364
rwbb: 363
read(): 76,peek: null, blockLength:363
rwbb: 362
read(): 101,peek: null, blockLength:362
rwbb: 361
read(): 97,peek: null, blockLength:361
rwbb: 360
read(): 100,peek: null, blockLength:360
rwbb: 359
read(): 98,peek: null, blockLength:359
rwbb: 358
read(): 111,peek: null, blockLength:358
rwbb: 357
read(): 120,peek: null, blockLength:357
rwbb: 356
read(): 50,peek: null, blockLength:356
rwbb: 355
read(): 48,peek: null, blockLength:355
rwbb: 354
read(): 49,peek: null, blockLength:354
rwbb: 353
read(): 53,peek: null, blockLength:353
rwbb: 352
read(): 48,peek: null, blockLength:352
rwbb: 351
read(): 57,peek: null, blockLength:351
rwbb: 350
read(): 95,peek: null, blockLength:350
rwbb: 349
read(): 55,peek: null, blockLength:349
rwbb: 348
read(): 53,peek: null, blockLength:348
rwbb: 347
read(): 55,peek: null, blockLength:347
rwbb: 346
read(): 54,peek: null, blockLength:346
rwbb: 345
read(): 51,peek: null, blockLength:345
rwbb: 344
read(): 24,peek: null, blockLength:344
rwbb: 343
read(): 0,peek: null, blockLength:343
rwbb: 342
read(): 122,peek: null, blockLength:342
rwbb: 341
read(): 99,peek: null, blockLength:341
rwbb: 340
read(): 114,peek: null, blockLength:340
rwbb: 339
read(): 109,peek: null, blockLength:339
rwbb: 338
read(): 95,peek: null, blockLength:338
rwbb: 337
read(): 49,peek: null, blockLength:337
rwbb: 336
read(): 51,peek: null, blockLength:336
rwbb: 335
read(): 53,peek: null, blockLength:335
rwbb: 334
read(): 53,peek: null, blockLength:334
rwbb: 333
read(): 56,peek: null, blockLength:333
rwbb: 332
read(): 56,peek: null, blockLength:332
rwbb: 331
read(): 53,peek: null, blockLength:331
rwbb: 330
read(): 48,peek: null, blockLength:330
rwbb: 329
read(): 48,peek: null, blockLength:329
rwbb: 328
read(): 48,peek: null, blockLength:328
rwbb: 327
read(): 48,peek: null, blockLength:327
rwbb: 326
read(): 48,peek: null, blockLength:326
rwbb: 325
read(): 48,peek: null, blockLength:325
rwbb: 324
read(): 48,peek: null, blockLength:324
rwbb: 323
read(): 56,peek: null, blockLength:323
rwbb: 322
read(): 56,peek: null, blockLength:322
rwbb: 321
read(): 49,peek: null, blockLength:321
rwbb: 320
read(): 53,peek: null, blockLength:320
rwbb: 319
read(): 55,peek: null, blockLength:319
rwbb: 318
read(): 5,peek: null, blockLength:318
rwbb: 317
read(): 0,peek: null, blockLength:317
rwbb: 316
read(): 83,peek: null, blockLength:316
rwbb: 315
read(): 71,peek: null, blockLength:315
rwbb: 314
read(): 80,peek: null, blockLength:314
rwbb: 313
read(): 49,peek: null, blockLength:313
rwbb: 312
read(): 49,peek: null, blockLength:312
rwbb: 311
read(): 10,peek: null, blockLength:311
rwbb: 310
read(): 0,peek: null, blockLength:310
rwbb: 309
read(): 65,peek: null, blockLength:309
rwbb: 308
read(): 85,peek: null, blockLength:308
rwbb: 307
read(): 84,peek: null, blockLength:307
rwbb: 306
read(): 79,peek: null, blockLength:306
rwbb: 305
read(): 77,peek: null, blockLength:305
rwbb: 304
read(): 79,peek: null, blockLength:304
rwbb: 303
read(): 66,peek: null, blockLength:303
rwbb: 302
read(): 73,peek: null, blockLength:302
rwbb: 301
read(): 76,peek: null, blockLength:301
rwbb: 300
read(): 69,peek: null, blockLength:300
rwbb: 299
read(): 6,peek: null, blockLength:299
rwbb: 298
read(): 0,peek: null, blockLength:298
rwbb: 297
read(): 71,peek: null, blockLength:297
rwbb: 296
read(): 65,peek: null, blockLength:296
rwbb: 295
read(): 82,peek: null, blockLength:295
rwbb: 294
read(): 65,peek: null, blockLength:294
rwbb: 293
read(): 71,peek: null, blockLength:293
rwbb: 292
read(): 69,peek: null, blockLength:292
rwbb: 291
read(): 13,peek: null, blockLength:291
rwbb: 290
rwbb: 289
read(): 74,peek: null, blockLength:289
rwbb: 288
read(): 79,peek: null, blockLength:288
rwbb: 287
read(): 83,peek: null, blockLength:287
rwbb: 286
read(): 69,peek: null, blockLength:286
rwbb: 285
read(): 80,peek: null, blockLength:285
rwbb: 284
read(): 72,peek: null, blockLength:284
rwbb: 283
read(): 32,peek: null, blockLength:283
rwbb: 282
read(): -1,peek: null, blockLength:282
rwbb: 281
read(): -1,peek: null, blockLength:281
rwbb: 280
read(): -1,peek: null, blockLength:280
Exception:Num of bytes skipped:-1, 280
EventDataDeserializationException:java.io.EOFException , 391 , 0
 oncommunication failure: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1443605718000, eventType=WRITE_ROWS, serverId=22172059, headerLength=19, dataLength=391, nextPosition=416904, flags=0}

2015-10-09 04:20:55,875 WARN  BinLogReader [BinlogReader-172_31_231_58] - Listener: Communication failure, BinLog: bin.006480 416494 clientServerId: 655556956 Cause: java.io.EOFException Exception: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1443605718000, eventType=WRITE_ROWS, serverId=22172059, headerLength=19, dataLength=391, nextPosition=416904, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:191)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:154)
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:612)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:385)
        at com.zoho.mysqlbackup.agent.BinLogReader.connect(BinLogReader.java:294)
        at com.zoho.mysqlbackup.agent.BinLogReader.readBinLog(BinLogReader.java:268)
        at com.zoho.mysqlbackup.agent.BinLogReader.run(BinLogReader.java:186)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:187)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:48)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:150)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:99)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:183)
        ... 6 more



In the above case, event data length is showing as 391, and it is reading upto 280 and throwing error.

**Comment by shyiko** [comment] 2015-10-10 05:53
Hi Syed. I've been going all over the code for the last half an hour trying to find any clues to what may be happening. I've found few major f* ups (namely 89d64ebc97db3f8696e82cb285e9ea41c60e32cf and 0c685a545f261eddfb1b8eaa91f31252d11ccc6c) and so it seems like I will be releasing 0.2.4 ASAP. Depending on what version of mysql-binlog-connector-java you are using (it's 0.2.3 regression) you may or may not be affected.

BUT: if there were no read(byte[], ...) calls and only read() then it looks like server is just closing the connection (-1 means EOF after all). I would check mysql logs and if nothing is there check tcp link.

**Closed by shyiko** 2015-10-10 05:53 UTC

**Comment by shyiko** [comment] 2015-10-10 07:04
Okay, I've uploaded 0.2.4 to Maven Central but neither of bugs that I've mentioned could result in what you have described. 

> BUT: if there were no read(byte[], ...) calls and only read() then it looks like server is just closing the connection (-1 means EOF after all). I would check mysql logs and if nothing is there would probably look into the tcp link.

**Comment by syed72** [comment] 2015-10-11 12:54
Thanks shyiko, But inputStream.read() returns -1 (even if the blocklength didnt reach to 0 or -1. i.e., actual eof not reached).

By the way I will try with 0.2.4.

**Comment by syed72** [comment] 2015-10-11 15:08
Listener: Communication failure, BinLog: bin.006490 411175 clientServerId: 1949304727 Cause: java.io.EOFException Exception: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1443611623000, eventType=UPDATE_ROWS, serverId=22172059, headerLength=19, dataLength=241, nextPosition=411435, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:191)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:154)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:612)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:385)
        at com.zoho.mysqlbackup.agent.BinLogReader.connect(BinLogReader.java:294)
        at com.zoho.mysqlbackup.agent.BinLogReader.readBinLog(BinLogReader.java:268)
        at com.zoho.mysqlbackup.agent.BinLogReader.run(BinLogReader.java:186)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:99)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readBitSet(ByteArrayInputStream.java:107)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:72)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:70)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:183)
        ... 6 more


Same EOFException in fill() method.

**Comment by shyiko** [comment] 2015-10-11 19:43
> inputStream.read() returns -1 (even if the blocklength didnt reach to 0 or -1. i.e., actual eof not reached).

Check out the javadocs for [read and read(byte[], ...)](http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html). -1 means EOF. blockLength is strictly synthetic to keep EventDataDeserializer within data boundaries. If stream gets closed in the middle of data deserialization - it's expected to fail (read will return -1 even if blockLength hasn't been reached).

**Comment by syed72** [comment] 2015-10-12 04:16
input stream getting closed? What may be the actual reason input stream getting closed?

**Comment by wushujames** [comment] 2015-10-12 08:03
@syed72, I haven't been following this thread too closely, but I saw your last question asking about your connection being closed.

The MySQL server can disconnect a client (in this case, mysql-binlog-connector-java) if it wants to. In particular, if a client is sitting there and not doing anything (not even polling for the latest binlog), the server might think that the client is idle and will proactively disconnect it.

You said this happens when you have lag of more than 1 day. In that case, what might be happening is:
1) mysql-binlog-connector-java downloads part of the binlog that has X number of records in it, and starts to process it.
2) It takes a "long" time to process the X records.
3) The server thinks you took too "long" to process the events and disconnects you.

You should verify this yourself, it's been a little while since I last ran into this.

I don't remember the setting in my.cnf that configures this, but I googled for "mysql disconnect client timeout" and saw some related articles. Or "mysql disconnect replication timeout" or something like that.

**Comment by syed72** [comment] 2015-10-12 08:20
Thanks @wushujames for giving a tip on this, 
Whatever u said may be the reason, i will check with the configurations on MySQL
That's happening quite frequently for me, Whenever the client is not in sync with master MySQL(lag in hours or > more than that), can u share any general my.cnf configurations(may be whatever u r using my.cnf file ).

This is the only issue i'm facing in the client side

**Comment by wushujames** [comment] 2015-10-12 08:26
I don't have a my.cnf I can share. I was doing this on some throw-away docker container, and I don't have anything around.

Btw, you can perform a disconnect at the server side by doing something like this: https://dev.mysql.com/doc/refman/5.0/en/show-processlist.html. That would at least help you see if you are getting the same symptoms.

**Comment by syed72** [comment] 2015-10-12 08:38
this is one of the row which is related to binlog reading

*************************** 99. row ***************************
     Id: 11688
   User: root
   Host: xxx.xx.xx.x:35355
     db: NULL
Command: Binlog Dump
   Time: 255
  State: Writing to net
   Info: NULL

**Comment by syed72** [comment] 2015-10-12 10:09
@wushujames I just debugged the issue by decreasing this 2 timeouts in mysq local setup, and i reproduced the issue, net_write_timeout , net_read_timeout. Could you please tell me, this is what the things you were referring to ?
