### ISSUE TITLE
question on serialization

### ISSUE THREAD

**Issue by berryma4** [shyiko/mysql-binlog-connector-java#182] opened 2017-10-19 20:51 UTC
I'm looking to distribute the binlog info to other servers, much like #33 

In the BinaryLogCLient.EventListener I have (shorted for clarity):
```java
                    ByteArrayEventData data = (ByteArrayEventData)event.getData();
                    EventHeaderV4 header = event.getHeader();
                    byte[] packet = new byte[19 + data.getData().length];
                    ByteBuffer buf = ByteBuffer.wrap(packet);
                    buf.order(ByteOrder.LITTLE_ENDIAN);
                    buf.putInt((int)(header.getTimestamp()));
                    buf.put((byte)(header.getEventType().ordinal()));
                    buf.putInt((int)(header.getServerId()));
                    buf.putInt((int)(header.getEventLength()));
                    buf.putInt((int)(header.getNextPosition()));
                    buf.putShort((short)(header.getFlags()));
                    buf.put(data.getData());
                    buf.flip();
                    Producer.send(packet).get();
                    buf.clear();
``` 
On the listening replicate, I would like to forward these events.  But, I get the mysqlbinlog error:
``` bash
ERROR: Error in Log_event::read_log_event(): 'Found invalid event in binary log', data_len: 1340, event_type: 23
ERROR: Could not read entry at offset 4: Error in log format or read error.
```
It seems the header is read fine, but the event data is not.
On the replicate, I'm writing the byte array to a file, then applying it with mysqlbinlog:
```java
                    byte[] binlog = new byte[MAGIC_HEADER.length+remaining.length];
                    ByteBuffer binlogBuf = ByteBuffer.wrap(binlog);
                    binlogBuf.order(ByteOrder.LITTLE_ENDIAN);
                    binlogBuf.put(MAGIC_HEADER);
                    binlogBuf.put(remaining);
                    binlogBuf.flip();
                    FileUtils.writeByteArrayToFile(tempBinlogFile, binlog, false);
                    binlogBuf.clear();
                    dump(mysqlbinlogProcessBuilder, tempFile);
                    load(mysqlProcessBuilder, tempFile);
```
First, this seems hacky, is there a better way to apply an event to the replicate.  Second, why is it unable to apply this event data?  Is the offset wrong?

Thank you for the help.

**Comment by shyiko** [comment] 2017-10-20 11:01
Hi.

> First, this seems hacky, is there a better way to apply an event to the replicate. 

Do you really need `mysql-binlog-connector-java` (in other words, why not to use native replication)? 

> Second, why is it unable to apply this event data?

Can you read the file you have generated with [BinaryLogFileReader](https://github.com/shyiko/mysql-binlog-connector-java#reading-binary-log-file)? If the answer is yes - [checksum](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java#L213) might be the problem. If not - serialization logic is broken.
 
(I'm closing this issue on the basis that it's not a bug or feature request, but feel free to continue the discussion).

**Closed by shyiko** 2017-10-20 11:01 UTC

**Comment by berryma4** [comment] 2017-10-20 16:51
First part, ... I unfortunately can't use native replication (I need to pass data through some security checks).

Second, using the BinaryLogFileReader on the data helps.  It does read the file (but errors on the previous TableMapEventData missing on the next event, which is a different error).
Wouldn't a checksum error give a checksum error?
Any ideas on how to fix this, if it is the checksum?  I see you remove it from the first bytes of the body.  Could I get it back, or recompute it with the byte array?

Thank you again.

```java
45 bytes
Binlog
Event{header=EventHeaderV4{timestamp=0, eventType=ROTATE, serverId=1, headerLength=19, dataLength=26, nextPosition=0, flags=32}, data=RotateEventData{binlogFilename='mariadb-bin.000081', binlogPosition=38252}}

245 bytes
Binlog
Event{header=EventHeaderV4{timestamp=961581104000, eventType=FORMAT_DESCRIPTION, serverId=1, headerLength=19, dataLength=226, nextPosition=0, flags=0}, data=FormatDescriptionEventData{binlogVersion=4, serverVersion='10.1.13-MariaDB-1~jessielog', headerLength=19}}

38 bytes
Binlog
Event{header=EventHeaderV4{timestamp=976163104000, eventType=QUERY, serverId=1, headerLength=19, dataLength=19, nextPosition=38290, flags=8}, data=QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='BEGIN'}}

51 bytes
Binlog
Event{header=EventHeaderV4{timestamp=976163104000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=32, nextPosition=38341, flags=0}, data=TableMapEventData{tableId=28, database='olog', table='entries', columnTypes=3, 18, -2, columnMetadata=0, 0, 63233, columnNullability={}}}
ERROR: Error in Log_event::read_log_event(): 'Found invalid event in binary log' at offset: 4  data_len: 51  event_type: 19
ERROR: Could not read entry at offset 4: Error in log format or read error.

40 bytes
Binlog
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=976163104000, eventType=WRITE_ROWS, serverId=1, headerLength=19, dataLength=21, nextPosition=38381, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:184)
        at com.github.shyiko.mysql.binlog.BinaryLogFileReader.readEvent(BinaryLogFileReader.java:82)
        at Consumer.processPacket(Consumer.java:126)
        at Consumer.lambda$runConsumer$0(Consumer.java:86)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at Consumer.runConsumer(Consumer.java:85)
        at ConsumerOlog.main(Consumer.java:19)
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:28. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:98)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:210)
        ... 7 more

```

**Comment by shyiko** [comment] 2017-10-20 21:56
@berryma4 are you trying to apply events one by one? This won't work. Events like FORMAT_DESCRIPTION are expected to be present in the stream (in other words, client (like mysqlbinlog) won't function properly if some of the events like FORMAT_DESCRIPTION or TABLE_MAP before *_ROWS are missing).

**Comment by berryma4** [comment] 2017-10-23 15:50
I was.  And, I see this won't work.

Is there anyway to stream events to mysql? (other than implementing a master binlog server, which the replicate mysql would connect, ask for events, etc.).

I tried a very cheap way for testing.  I'm streaming to the mysqlbinlog command, then streaming to the mysql command.  This seems to work, but also is a bit of a hack.
